# Generated by Django 5.2.4 on 2025-07-25 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_privatechatroom_privatemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='sender',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='participants',
            field=models.ManyToManyField(related_name='private_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
